### ISSUE TITLE
Authentication checker using JWT for sign in and sign up 

### ISSUE THREAD

**Issue by surendar-05** [itsmohit097/MediHub#10]
Assign this issue to me i want to work on this under ?GSSOC'24

**Comment by ArtiGaund** [comment]
@itsmohit097 Can you assign this issue to me ? I already have authentication in ReactJS using Mongoose and MongoDB.

**Comment by thefarhanahmad** [comment]
Hi there! I'm excited to contribute to this project and would love to work on this issue. Could you please assign it to me? Thanks!

**Comment by itsmohit097** [comment]
#### This repository is not valid.
#### Sorry for the inconvenience.
### Please make your valuable contribution here https://github.com/itsmohit097/medi-hub

**Comment by itsmohit097** [comment]
#### This repository is not valid.
#### Sorry for the inconvenience.
### Please make your valuable contribution here https://github.com/itsmohit097/medi-hub
