### ISSUE TITLE
Footer Design

### ISSUE THREAD

**Issue by Prithwi32** [itsmohit097/MediHub#11]
Key Points achieved:
*Footer UIUX improved
*Responsiveness

**Comment by Prithwi32** [comment]
@itsmohit097 Please could you assign me this issue under GSSoC'24

**Comment by thefarhanahmad** [comment]
Hi there! I'm excited to contribute to this project and would love to work on this issue. Could you please assign it to me? Thanks!

**Comment by itsmohit097** [comment]
#### This repository is not valid.
#### Sorry for the inconvenience.
### Please make your valuable contribution here https://github.com/itsmohit097/medi-hub
