### ISSUE TITLE
Login and SignUP page design

### ISSUE THREAD

**Issue by Prithwi32** [itsmohit097/MediHub#12]
*Both Login and SignUp page design with tailwind CSS
*Responsiveness will be added

**Comment by Prithwi32** [comment]
@itsmohit097 Please could you assign me this issue under GSSoC'24

**Comment by thefarhanahmad** [comment]
Hi there! I'm excited to contribute to this project and would love to work on this issue. Could you please assign it to me? Thanks!

**Comment by Himanshityagii24** [comment]
Hello, can you assign me this task I can design as well as can  add backend to the login and signup-page using NODE.JS EXPRESS.JS,MONGODB and JAVASCRIPT.

**Comment by itsmohit097** [comment]
#### This repository is not valid.
#### Sorry for the inconvenience.
### Please make your valuable contribution here https://github.com/itsmohit097/medi-hub
