### ISSUE TITLE
Add Appointment Section Backend

### ISSUE THREAD

**Issue by Surajit0573** [itsmohit097/MediHub#14]
Currently, there is nothing in Appointments sections I would like to add the backend & frontend page for appointments. All booked appointments by patient will be listed in this section. Please assign me under Gssoc'24.

**Comment by itsmohit097** [comment]
#### This repository is not valid.
#### Sorry for the inconvenience.
### Please make your valuable contribution here https://github.com/itsmohit097/medi-hub
