### ISSUE TITLE
Add About Us Page

### ISSUE THREAD

**Issue by Surajit0573** [itsmohit097/MediHub#15]
I want to add a About Us page. Please assign me under Gssoc'24.

**Comment by SumitKumar-17** [comment]
@itsmohit097  I want to work on this ssue. Can you assign this issue to me under GSSoc'24?

**Comment by itsmohit097** [comment]
#### This repository is not valid.
#### Sorry for the inconvenience.
### Please make your valuable contribution here https://github.com/itsmohit097/medi-hub
