### ISSUE TITLE
All Doctors Page Design

### ISSUE THREAD

**Issue by aindree-2005** [itsmohit097/MediHub#7]
Designing an all doctors page, with json servers and filtering option by department

**Comment by aindree-2005** [comment]
@itsmohit097  can I work on this?

**Comment by thefarhanahmad** [comment]
Hi there! I'm excited to contribute to this project and would love to work on this issue. Could you please assign it to me? Thanks!

**Comment by itsmohit097** [comment]
#### This repository is not valid.
#### Sorry for the inconvenience.
### Please make your valuable contribution here https://github.com/itsmohit097/medi-hub
