### ISSUE TITLE
No Login/SignUp page. I'll add the authentication for the application.

### ISSUE THREAD

**Issue by shalininukella** [itsmohit097/MediHub#8]
@itsmohit097 I would like to add the login and sign up pages for the application. 

I would request you assign this issue to me used GSSOC'24.

**Comment by thefarhanahmad** [comment]
Hi there! I'm excited to contribute to this project and would love to work on this issue. Could you please assign it to me? Thanks!

**Comment by Himanshityagii24** [comment]
Hello, I want to contribute to this project by adding login and signup page , I can add backend for the pages also by using NODE.JS,EXPRESS.JS , JAVASCRIPT ,MONGODB.

**Comment by itsmohit097** [comment]
#### This repository is not valid.
#### Sorry for the inconvenience.
### Please make your valuable contribution here https://github.com/itsmohit097/medi-hub
